name: Jest-Unit-Tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

# jobs:
#   # https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
jobs:
  # client_tests:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: client
  #   name: client tests
  #   steps:
  #     - run: npm run test a
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - run: pwd
  server_tests:
    runs-on: ubuntu-latest
    name: server tests
    working-directory: ./server
    steps:
      - run: npm run test
    